source "https://rubygems.org"

gem "rack", "~> 3.0"
gem "rack-session"
gem "rackup"
gem "bcrypt"
gem "puma"
gem "pg"
gem "activerecord"
gem "otr-activerecord"
gem "rake"
gem "erb"
gem "dotenv"
gem "tilt", "~> 2.7"
gem "erubi", "~> 1.13"
